tinymce.addI18n('syno', {
	'Attach file':		_T('tinymce', 'attach_file'),
	'Align left':		_T('tinymce', 'align_left'),
	'Align center':		_T('tinymce', 'align_center'),
	'Align right':		_T('tinymce', 'align_right'),
	'Justify':			_T('tinymce', 'align_justify'),
	'Font Family':		_T('tinymce', 'font_family'),
	'Font Size':		_T('tinymce', 'font_size'),
	'Text color':		_T('tinymce', 'text_color'),
	'Background color':	_T('tinymce', 'background_color'),
	'Bold':				_T('tinymce', 'bold'),
	'Italic':			_T('tinymce', 'italic'),
	'Clear formatting': _T('tinymce', 'clear_formatting'),
	'Underline':		_T('tinymce', 'underline'),
	'Strikethrough':	_T('tinymce', 'strikethrough'),
	'Subscript':		_T('tinymce', 'subscript'),
	'Superscript':		_T('tinymce', 'superscript'),
	'Numbered list':	_T('tinymce', 'numbered_list'),
	'Bullet list':		_T('tinymce', 'bullet_list'),
	'Increase indent':	_T('tinymce', 'increase_indent'),
	'Decrease indent':	_T('tinymce', 'decrease_indent'),
	'Horizontal line':	_T('tinymce', 'horizontal_line'),
	'Undo':				_T('texteditor', 'Undo'),
	'Redo':				_T('texteditor', 'Redo')
});
